# Generated by Django 4.0.5 on 2022-06-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='media/thumbnails/default_image.png', upload_to='media/'),
        ),
    ]
