# Generated by Django 4.0.5 on 2022-06-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default_image.png', upload_to='thumbnails/'),
        ),
    ]
