# Generated by Django 4.0.5 on 2022-06-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_featured_preview_alter_post_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et tempor nisl.', max_length=85),
        ),
    ]
