# Generated by Django 4.0.5 on 2022-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='https://media.griffinsteffy.com/media//media/thumbnails/default_image.png', upload_to='https://media.griffinsteffy.com/media/thumbnails/'),
        ),
    ]
