# Generated by Django 4.0.5 on 2022-07-02 17:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/grifinsteffy/Documents/griffinsteffy.com/media/'), upload_to='blog/templates/posts/'),
        ),
    ]
