# Generated by Django 3.0.4 on 2022-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20220727_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_preview',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et tempor nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices dolor.', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et tempor nisl.', max_length=150),
        ),
    ]
