# Generated by Django 3.0.4 on 2022-07-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20220727_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et tempor nisl.', max_length=85),
        ),
    ]
